### ISSUE TITLE
Adding the Request Info bot

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/.github#2]
### Proposed change

It would be nice to have a bot that follows up on opened PRs or issues that don't provide any descriptions and asks the users for more information.

### Alternative options

* Don't allow blank GitHub issues (i.e. allow only feature requests or bug reports that should follow the templates)
* Use a Pull Request  template

### Who would use this feature?

This would help speed up the process of reviewing PRs and answering issues.
So, I believe it would be beneficial for maintainers and contributors alike. 

### (Optional): Suggest a solution

Configure the [Request Info bot](https://github.com/apps/request-info) for our repositories:

```
The bot requests more info from newly opened Pull Requests and Issues
that contain either default titles or whose description is left blank.
It does so by taking data from a .github/config.yml.
```

**Comment by GeorgianaElena** [comment]
I set up the bot on my `.github` repo here: https://github.com/GeorgianaElena/.github/issues/3

The only thing I'm not happy about is that if we choose to add the `needs-more-info` label and the contributor updates their comment, the label is not removed by the bot.

@betatim, what do you think about this (the bot message is more or less the message that you posted on a PR opened in JH that didn't provide a description)?

**Comment by choldgraf** [comment]
I like it! re: removing the tag, maybe it's fine for a member to have to manually do this anyway? Since we don't know whether the person actually added helpful info?

**Comment by betatim** [comment]
I like it. Can we make the bot link to the PR/issue templates so we can give people a pointer towards what we expect?
